services:
  - type: web
    name: wiom-dsat-tool
    runtime: python
    rootDir: dsat_app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wiom-dsat-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: wiom-dsat-db
    databaseName: dsatdb
    plan: free
